import http from './http'

export const admin = {
  dashboard: () => http.get('/api/v1/admin/dashboard'),
  dashboardCharts: () => http.get('/api/v1/admin/dashboard/charts'),
  users: (params: Record<string, unknown>) => http.get('/api/v1/admin/users', { params }),
  createUser: (body: Record<string, unknown>) => http.post('/api/v1/admin/users', body),
  updateUser: (id: number, body: Record<string, unknown>) => http.put(`/api/v1/admin/users/${id}`, body),
  setUserRoles: (id: number, role_ids: number[]) => http.post(`/api/v1/admin/users/${id}/roles`, { role_ids }),
  resetPassword: (id: number) => http.post(`/api/v1/admin/users/${id}/reset-password`),
  roles: () => http.get('/api/v1/admin/roles'),
  createRole: (body: Record<string, unknown>) => http.post('/api/v1/admin/roles', body),
  updateRole: (id: number, body: Record<string, unknown>) => http.put(`/api/v1/admin/roles/${id}`, body),
  deleteRole: (id: number) => http.delete(`/api/v1/admin/roles/${id}`),
  roleMenus: (id: number) => http.get(`/api/v1/admin/roles/${id}/menus`),
  setRoleMenus: (id: number, menu_ids: number[]) => http.put(`/api/v1/admin/roles/${id}/menus`, { menu_ids }),
  menuTree: () => http.get('/api/v1/admin/menus/tree'),
  createMenu: (body: Record<string, unknown>) => http.post('/api/v1/admin/menus', body),
  updateMenu: (id: number, body: Record<string, unknown>) => http.put(`/api/v1/admin/menus/${id}`, body),
  deleteMenu: (id: number) => http.delete(`/api/v1/admin/menus/${id}`),
  categories: () => http.get('/api/v1/admin/categories'),
  createCategory: (body: Record<string, unknown>) => http.post('/api/v1/admin/categories', body),
  updateCategory: (id: number, body: Record<string, unknown>) => http.put(`/api/v1/admin/categories/${id}`, body),
  deleteCategory: (id: number) => http.delete(`/api/v1/admin/categories/${id}`),
  itemStatusDict: () => http.get('/api/v1/admin/dictionary/item-status'),
  createItemStatusDict: (body: Record<string, unknown>) => http.post('/api/v1/admin/dictionary/item-status', body),
  updateItemStatusDict: (id: number, body: Record<string, unknown>) =>
    http.put(`/api/v1/admin/dictionary/item-status/${id}`, body),
  deleteItemStatusDict: (id: number) => http.delete(`/api/v1/admin/dictionary/item-status/${id}`),
  items: (params: Record<string, unknown>) => http.get('/api/v1/admin/items', { params }),
  deleteItem: (id: number) => http.delete(`/api/v1/admin/items/${id}`),
  pendingClaims: (params: Record<string, unknown>) => http.get('/api/v1/admin/claims/pending', { params }),
  myReviewedClaims: (params: Record<string, unknown>) => http.get('/api/v1/admin/claims/reviewed/mine', { params }),
  claimDetail: (id: number) => http.get(`/api/v1/admin/claims/${id}/detail`),
  adminApproveClaim: (id: number) => http.post(`/api/v1/admin/claims/${id}/approve`),
  adminRejectClaim: (id: number, reject_reason: string) =>
    http.post(`/api/v1/admin/claims/${id}/reject`, { reject_reason }),
  loginLogs: (params: Record<string, unknown>) => http.get('/api/v1/admin/logs/login', { params }),
  operationLogs: (params: Record<string, unknown>) => http.get('/api/v1/admin/logs/operation', { params }),
  exceptionLogs: (params: Record<string, unknown>) => http.get('/api/v1/admin/logs/exception', { params }),
  exceptionDetail: (id: number) => http.get(`/api/v1/admin/logs/exception/${id}`),
  exportLogin: () => (window.location.href = '/api/v1/admin/logs/login/export'),
  exportOperation: () => (window.location.href = '/api/v1/admin/logs/operation/export'),
  exportException: () => (window.location.href = '/api/v1/admin/logs/exception/export'),
  getHomeListPageSize: () => http.get('/api/v1/admin/settings/home-list-page-size'),
  setHomeListPageSize: (page_size: number) =>
    http.put('/api/v1/admin/settings/home-list-page-size', { page_size }),
}
